[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
dotenvy = "0.15.7"
once_cell = "1.21.3"
tokio = "1.47.1"
tokio-cron-scheduler = "0.14.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
