name: Python CI

on:
  push:
    branches: [main, development]
    paths:
      - 'client/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [main, development]
    paths:
      - 'client/**'
      - '.github/workflows/python-ci.yml'
  workflow_dispatch:

jobs:
  python-check:
    name: Python Format Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
    
    - name: Install dependencies
      run: |
       cd client
       pip install -r requirements.txt
       pip install -r requirements-dev.txt
    
    - name: Check client formatting
      run: make check-client

  python-test:
    name: Python Test
    runs-on: ubuntu-latest
    env:
      CLIENT_TOKEN: Lorem_ipsum
      CLIENT_PREFIX: Lorem_ipsum
      SERVER_WS_URL: Lorem_ipsum
      SERVER_API_URL: Lorem_ipsum
      OWNER_ID: 1234567
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('client/requirements*.txt', 'client/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        cd client
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run client tests
      run: cd client && pytest